#!/usr/bin/env bash
# =============================================================================
# Regenerates deployment/gateway-routes-local.yml from the gateway's in-jar
# application-local.yml.
#
# WHY: that file hardcodes every route to http://localhost:<port>. Correct when
# services run on your HOST via bootRun; wrong inside Docker, where `localhost`
# is the gateway container itself — every proxied call fails with
# "Connection refused: localhost/127.0.0.1:8082" and the caller sees 503.
# This script republishes the SAME route list with compose service names, which
# resolve on the onified-network bridge.
#
# Routes are copied VERBATIM apart from the `uri:` host, so predicates, filters
# and ordering stay in lockstep with the source. Re-run after any route change
# upstream, otherwise the mounted override serves a stale route table.
#
# Usage:  bash deployment/gen-gateway-routes.sh
# =============================================================================
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$REPO_ROOT/services/platform/gateway/src/main/resources/application-local.yml"
OUT="$REPO_ROOT/deployment/gateway-routes-local.yml"

[ -f "$SRC" ] || { echo "source not found: $SRC" >&2; exit 1; }

# Locate the routes list: from the `routes:` key to the line before the next
# key at the same indent. Derived rather than hardcoded so upstream edits that
# shift line numbers don't silently truncate the copy.
START="$(grep -n '^          routes:$' "$SRC" | head -1 | cut -d: -f1)"
[ -n "$START" ] || { echo "could not locate 'routes:' block in $SRC" >&2; exit 1; }
END="$(awk -v s="$START" 'NR>s && /^          [a-zA-Z_-]+:/ {print NR-1; exit}' "$SRC")"
[ -n "$END" ] || { echo "could not locate end of routes block" >&2; exit 1; }

echo "routes block: lines $START..$END of $(basename "$SRC")"

{
  cat <<'HDR'
# =============================================================================
# GENERATED by deployment/gen-gateway-routes.sh — DO NOT EDIT BY HAND.
#
# Gateway route URIs for the CONTAINERISED local stack. The in-jar
# application-local.yml hardcodes http://localhost:<port>, which inside Docker
# resolves to the gateway container itself (503 on every proxied call). These
# are the same routes with compose service names substituted.
#
# Bind-mounted to /app/config/application-local.yml by docker-compose.yml.
# WORKDIR is /app and Spring Boot's file:./config/ outranks the classpath, so
# this routes list replaces the in-jar one (lists are replaced, not merged).
# Every other local-profile property still comes from the jar.
#
# NOT REMAPPED, deliberately:
#   * SSO routes (localhost:8091) — the sso service is commented out of
#     docker-compose.yml, so there is no container to point at.
#   * *.svc.cluster.local routes (AI capability services, observability,
#     fieldmap, market-map) — no local equivalent exists; they 503 locally
#     exactly as they did before.
# =============================================================================

spring:
  cloud:
    gateway:
      server:
        webflux:
HDR
  sed -n "${START},${END}p" "$SRC" | awk '
  /uri:/ {
    sub(/localhost:8081/, "content:8081");
    sub(/localhost:8082/, "identity:8082");
    sub(/localhost:8084/, "billing-subscription:8084");
    sub(/localhost:8085/, "platform-data:8085");
    sub(/localhost:8086/, "master-data:8086");
    sub(/localhost:8087/, "analytics:8087");
    sub(/localhost:8088/, "governance:8088");
    sub(/localhost:8089/, "notification:8089");
    sub(/localhost:8090/, "integration:8090");
    sub(/localhost:8092/, "work-management:8092");
    sub(/localhost:8093/, "workflow:8093");
    sub(/localhost:8094/, "cargo:8094");
    sub(/localhost:8095/, "job-orchestration:8095");
    sub(/localhost:8096/, "geo:8096");
  }
  { print }'
} > "$OUT"

echo "wrote $OUT"
echo "remapped route URIs:"
grep -oE 'uri: http://[a-z0-9-]+:[0-9]+' "$OUT" | sort | uniq -c | sort -rn
